"""Offline command recipes and conservative placeholder inspection.

Recipes are deliberately kept separate from ``topics.json``.  The latter is
the verbatim, citation-backed command catalogue; this module describes a
small set of *derived* executable variants that can be rendered only after
the user has supplied every safe parameter.  A caller can therefore use the
full catalogue for retrieval while refusing to guess parameters for commands
that do not have a recipe.

The JSON format is intentionally data-only and can be generated by
``scripts/sync_knowledge.py``.  The loader accepts the generated format and
is tolerant of an absent file so older installations continue to work.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal


SlotType = Literal["path", "port", "identifier", "value", "choice", "credential"]

# A placeholder can contain punctuation and spaces (for example
# ``<path/to/file>``), but never a newline or another angle bracket.  This is
# intentionally narrower than ``<[^>]+>`` so shell redirections such as
# ``< backup.sql`` can be handled without being mistaken for a slot.
PLACEHOLDER_RE = re.compile(r"(?<!<)<([^<>\r\n]+)>(?!>)")

# Forms that are examples/choices rather than parameters.  The generic
# inspector reports them as ``literal`` instead of prompting the user.  A
# recipe may still explicitly model one of these as a slot.
_NON_SLOT_NAMES = {
    "enter",
    "tab",
    "space",
    "80",
    "443",
    "8.8.8.8",
    "2.7.10",
    "0c01a9",
    "9a1743",
}
_CHOICE_RE = re.compile(r"^\[.+\]$")
_REDIRECTION_RE = re.compile(r"^\s*$")


@dataclass(frozen=True, slots=True)
class RecipeSlot:
    name: str
    label: str
    type: SlotType
    question: str = ""
    required: bool = True
    secret: bool = False
    validation: str = ""
    options: tuple[dict[str, str], ...] = ()
    default: str | None = None
    prompt_if_absent: bool = False

    @classmethod
    def from_dict(cls, payload: dict[str, Any], *, required: bool) -> "RecipeSlot":
        slot_type = str(payload.get("type") or "value")
        if slot_type not in {"path", "port", "identifier", "value", "choice", "credential"}:
            slot_type = "value"
        options = tuple(
            {"label": str(item.get("label", "")), "value": str(item.get("value", ""))}
            for item in payload.get("options", [])
            if isinstance(item, dict) and str(item.get("value", "")).strip()
        )
        return cls(
            name=str(payload.get("name") or "value"),
            label=str(payload.get("label") or payload.get("name") or "参数"),
            type=slot_type,  # type: ignore[arg-type]
            question=str(payload.get("question") or ""),
            required=required,
            secret=bool(payload.get("secret", slot_type == "credential")),
            validation=str(payload.get("validation") or ""),
            options=options,
            default=(str(payload["default"]) if payload.get("default") is not None else None),
            prompt_if_absent=bool(payload.get("prompt_if_absent", False)),
        )


@dataclass(frozen=True, slots=True)
class RecipeStep:
    id: str
    label: str
    merge: Literal["newline", "space"] = "newline"
    templates: dict[str, str] | None = None
    languages: dict[str, str] | None = None

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "RecipeStep":
        merge = str(payload.get("merge") or "newline")
        if merge not in {"newline", "space"}:
            merge = "newline"
        templates = payload.get("templates")
        languages = payload.get("languages")
        return cls(
            id=str(payload.get("id") or "step"),
            label=str(payload.get("label") or payload.get("id") or "步骤"),
            merge=merge,  # type: ignore[arg-type]
            templates={str(k): str(v) for k, v in templates.items()} if isinstance(templates, dict) else None,
            languages={str(k): str(v) for k, v in languages.items()} if isinstance(languages, dict) else None,
        )


@dataclass(frozen=True, slots=True)
class RecipeDerivedSlot:
    """A deterministic value composed from already-confirmed slots."""

    name: str
    type: SlotType
    expression: str

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "RecipeDerivedSlot":
        slot_type = str(payload.get("type") or "value")
        if slot_type not in {"path", "port", "identifier", "value", "choice", "credential"}:
            slot_type = "value"
        return cls(
            name=str(payload.get("name") or "value"),
            type=slot_type,  # type: ignore[arg-type]
            expression=str(payload.get("expression") or ""),
        )


@dataclass(frozen=True, slots=True)
class RecipeProvenance:
    source_id: str
    title: str
    source_url: str | None
    license: str
    revision: str
    path: str
    sha256: str
    kind: str
    role: str = "basis"

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "RecipeProvenance":
        return cls(
            source_id=str(payload.get("source_id") or ""),
            title=str(payload.get("title") or ""),
            source_url=(str(payload["source_url"]) if payload.get("source_url") else None),
            license=str(payload.get("license") or ""),
            revision=str(payload.get("revision") or ""),
            path=str(payload.get("path") or ""),
            sha256=str(payload.get("sha256") or ""),
            kind=str(payload.get("kind") or "project_authored"),
            role=str(payload.get("role") or "basis"),
        )


@dataclass(frozen=True, slots=True)
class CommandRecipe:
    recipe_id: str
    topic_id: str
    title: str
    description: str
    required_slots: tuple[RecipeSlot, ...]
    optional_slots: tuple[RecipeSlot, ...]
    derived_slots: tuple[RecipeDerivedSlot, ...]
    platforms: tuple[str, ...]
    shells: tuple[str, ...]
    steps: tuple[RecipeStep, ...]
    provenance: tuple[RecipeProvenance, ...]
    source_revision: str

    @property
    def slots(self) -> tuple[RecipeSlot, ...]:
        return (*self.required_slots, *self.optional_slots)

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "CommandRecipe":
        required = tuple(
            RecipeSlot.from_dict(item, required=True)
            for item in payload.get("required_slots", [])
            if isinstance(item, dict)
        )
        optional = tuple(
            RecipeSlot.from_dict(item, required=False)
            for item in payload.get("optional_slots", [])
            if isinstance(item, dict)
        )
        return cls(
            recipe_id=str(payload.get("recipe_id") or ""),
            topic_id=str(payload.get("topic_id") or ""),
            title=str(payload.get("title") or ""),
            description=str(payload.get("description") or ""),
            required_slots=required,
            optional_slots=optional,
            derived_slots=tuple(
                RecipeDerivedSlot.from_dict(item)
                for item in payload.get("derived_slots", [])
                if isinstance(item, dict)
            ),
            platforms=tuple(str(item) for item in payload.get("platforms", [])),
            shells=tuple(str(item) for item in payload.get("shells", [])),
            steps=tuple(
                RecipeStep.from_dict(item)
                for item in payload.get("steps", [])
                if isinstance(item, dict)
            ),
            provenance=tuple(
                RecipeProvenance.from_dict(item)
                for item in payload.get("provenance", [])
                if isinstance(item, dict)
            ),
            source_revision=str(payload.get("source_revision") or ""),
        )


class RecipeCatalog:
    """Load and validate the offline recipe bundle.

    ``load`` returns an empty list when a pre-2.5 knowledge directory has no
    recipes file.  Invalid JSON or duplicate identifiers is an installation
    error, matching ``KnowledgeCatalog``'s fail-closed behaviour.
    """

    def __init__(self, knowledge_dir: Path) -> None:
        self.knowledge_dir = knowledge_dir
        self.recipes: list[CommandRecipe] = []
        self.metadata: dict[str, Any] = {}

    def load(self) -> list[CommandRecipe]:
        path = self.knowledge_dir / "recipes.json"
        if not path.exists():
            self.recipes = []
            self.metadata = {"schema_version": 0, "recipe_revision": ""}
            return self.recipes
        payload = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(payload, dict):
            raise ValueError("recipes.json 必须是 JSON 对象")
        raw_recipes = payload.get("recipes", [])
        if not isinstance(raw_recipes, list):
            raise ValueError("recipes.json 的 recipes 必须是数组")
        recipes = [
            CommandRecipe.from_dict(item)
            for item in raw_recipes
            if isinstance(item, dict)
        ]
        if any(not recipe.recipe_id or not recipe.topic_id for recipe in recipes):
            raise ValueError("recipes.json 包含缺少 recipe_id 或 topic_id 的配方")
        if len({recipe.recipe_id for recipe in recipes}) != len(recipes):
            raise ValueError("recipes.json 包含重复 recipe_id")
        if any(not recipe.steps for recipe in recipes):
            raise ValueError("recipes.json 包含没有步骤的配方")
        self.recipes = recipes
        self.metadata = payload
        return self.recipes

    def by_id(self, recipe_id: str) -> CommandRecipe | None:
        return next((item for item in self.recipes if item.recipe_id == recipe_id), None)

    def for_topic(self, topic_id: str) -> list[CommandRecipe]:
        return [item for item in self.recipes if item.topic_id == topic_id]


def _strip_placeholder(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip()).casefold()


def classify_placeholder(name: str, *, command: str = "") -> str:
    """Classify one placeholder conservatively for generic fallback UX.

    This function is deliberately advisory.  Only explicit recipe slots may
    be rendered into executable output; a guessed classification is never
    enough to auto-fill a value.
    """

    normalized = _strip_placeholder(name)
    if normalized in _NON_SLOT_NAMES or _CHOICE_RE.fullmatch(name.strip()):
        return "literal"
    if any(token in normalized for token in ("password", "passwd", "token", "secret", "private_key", "credential")):
        return "credential"
    if normalized in {"port", "port_number", "localport", "remoteport"} or normalized.endswith("_port"):
        return "port"
    if any(token in normalized for token in ("path", "file", "dir", "directory", "folder", "filename", "backup.sql")):
        return "path"
    if any(token in normalized for token in ("branch", "commit", "tag", "repo", "repository", "database", "db", "table", "column", "user", "host", "image", "container", "key", "field", "channel")):
        return "identifier"
    # Redirection targets and shell snippets should remain templates unless a
    # curated recipe explicitly says otherwise.
    if command and re.search(rf"<\s*{re.escape(name.strip())}\s*>", command):
        return "value"
    return "value"


def inspect_placeholders(command: str) -> list[dict[str, str]]:
    """Return unique, typed placeholders found in a command.

    The result includes ``name``, ``type`` and ``raw``.  The parser does not
    attempt to parse every angle-bracket expression in shell/SQL syntax and
    therefore errs toward a required value instead of silently claiming that
    the command is executable.
    """

    found: list[dict[str, str]] = []
    seen: set[str] = set()
    for match in PLACEHOLDER_RE.finditer(command):
        name = match.group(1).strip()
        normalized = _strip_placeholder(name)
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        kind = classify_placeholder(name, command=command)
        found.append({"name": name, "type": kind, "raw": match.group(0)})
    return found


def unresolved_placeholders(command: str) -> list[dict[str, str]]:
    """Alias used by planners when deciding between direct and template mode."""

    return [item for item in inspect_placeholders(command) if item["type"] != "literal"]


def has_unresolved_placeholders(command: str) -> bool:
    return bool(unresolved_placeholders(command))


__all__ = [
    "CommandRecipe",
    "PLACEHOLDER_RE",
    "RecipeCatalog",
    "RecipeDerivedSlot",
    "RecipeProvenance",
    "RecipeSlot",
    "RecipeStep",
    "classify_placeholder",
    "has_unresolved_placeholders",
    "inspect_placeholders",
    "unresolved_placeholders",
]
